name: FLPoison
channels:
  - defaults
dependencies:
  - python=3.10.16
  - pip=25.0
  - setuptools=75.8.0
  - wheel=0.45.1
  - ca-certificates=2024.12.31
  - openssl=3.0.15
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - zlib=1.2.13
  - xz=5.4.6
  - bzip2=1.0.8
  - libffi=3.4.4
  - pip:
      - captum
      - contourpy==1.3.1
      - cycler==0.12.1
      - filelock==3.17.0
      - fonttools==4.56.0
      - fsspec==2025.2.0
      - hdbscan==0.8.40
      - jinja2==3.1.5
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.2
      - packaging==24.2
      - pillow==11.1.0
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - rarfile==4.2
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - six==1.17.0
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - torch==2.6.0
      - torchvision==0.21.0
      - typing-extensions==4.12.2
      - unrar==0.4
